language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-source

script:
  - vendor/bin/phpunit

